name: weather_wise_app
description: Weather Forecast.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.0
  hydrated_bloc: ^9.0.0
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  page_transition: ^2.0.9
  auth0_flutter: ^1.0.2
  flutter_dotenv: ^5.0.2
  google_fonts: ^3.0.1
  cool_alert: ^1.1.0
  weather_icons: ^3.0.0
  shared_preferences: ^2.0.17
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/onboarding/
    - lib/assets/images/welcome/
    - lib/assets/images/shared/
    - lib/assets/images/logos/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lib/assets/images/logos/logo.png"
